
PRODUCTOS_SIMULADOS = [
    {'nombre': 'Smartphone 550', 'descripcion': 'Teléfono inteligente de última generación', 'cantidad': 33, 'precio': 437.97, 'categoria': 'Electrónica'},
    {'nombre': 'Laptop 773', 'descripcion': 'Portátil ligera y potente para uso diario', 'cantidad': 40, 'precio': 170.67, 'categoria': 'Electrónica'},
    {'nombre': 'Auriculares 723', 'descripcion': 'Auriculares Bluetooth con cancelación de ruido', 'cantidad': 32, 'precio': 382.05, 'categoria': 'Electrónica'},
    {'nombre': 'Tablet 449', 'descripcion': 'Pantalla táctil de alta resolución', 'cantidad': 30, 'precio': 63.12, 'categoria': 'Electrónica'},
    {'nombre': 'Smartwatch 184', 'descripcion': 'Reloj inteligente con monitor de salud', 'cantidad': 0, 'precio': 247.95, 'categoria': 'Electrónica'},
    {'nombre': 'Camiseta 216', 'descripcion': 'Camiseta de algodón de varios colores', 'cantidad': 40, 'precio': 194.28, 'categoria': 'Ropa'},
    {'nombre': 'Pantalón 542', 'descripcion': 'Pantalón casual unisex', 'cantidad': 50, 'precio': 329.13, 'categoria': 'Ropa'},
    {'nombre': 'Chaqueta 937', 'descripcion': 'Chaqueta impermeable con capucha', 'cantidad': 39, 'precio': 46.41, 'categoria': 'Ropa'},
    {'nombre': 'Zapatillas 277', 'descripcion': 'Zapatillas deportivas cómodas', 'cantidad': 26, 'precio': 240.16, 'categoria': 'Ropa'},
    {'nombre': 'Gorro 827', 'descripcion': 'Gorro de lana para invierno', 'cantidad': 13, 'precio': 80.01, 'categoria': 'Ropa'},
    {'nombre': 'Arroz 402', 'descripcion': 'Arroz blanco de grano largo', 'cantidad': 36, 'precio': 448.42, 'categoria': 'Alimentos'},
    {'nombre': 'Aceite 827', 'descripcion': 'Aceite vegetal de cocina', 'cantidad': 16, 'precio': 331.1, 'categoria': 'Alimentos'},
    {'nombre': 'Leche 638', 'descripcion': 'Leche entera en envase de litro', 'cantidad': 5, 'precio': 272.33, 'categoria': 'Alimentos'},
    {'nombre': 'Pan 148', 'descripcion': 'Pan de molde integral', 'cantidad': 34, 'precio': 289.19, 'categoria': 'Alimentos'},
    {'nombre': 'Cereal 289', 'descripcion': 'Cereal de desayuno con frutas', 'cantidad': 24, 'precio': 207.69, 'categoria': 'Alimentos'},
    {'nombre': 'Muñeca 109', 'descripcion': 'Muñeca con ropa intercambiable', 'cantidad': 16, 'precio': 167.44, 'categoria': 'Juguetes'},
    {'nombre': 'Auto de juguete 606', 'descripcion': 'Coche pequeño a fricción', 'cantidad': 19, 'precio': 166.02, 'categoria': 'Juguetes'},
    {'nombre': 'Rompecabezas 632', 'descripcion': 'Puzzle de 100 piezas', 'cantidad': 9, 'precio': 123.77, 'categoria': 'Juguetes'},
    {'nombre': 'Pelota saltarina 914', 'descripcion': 'Pelota colorida para niños', 'cantidad': 7, 'precio': 193.99, 'categoria': 'Juguetes'},
    {'nombre': 'Bloques de construcción 103', 'descripcion': 'Bloques plásticos para armar', 'cantidad': 0, 'precio': 464.68, 'categoria': 'Juguetes'},
    {'nombre': 'Balón de fútbol 208', 'descripcion': 'Balón profesional tamaño 5', 'cantidad': 4, 'precio': 223.19, 'categoria': 'Deportes'},
    {'nombre': 'Raqueta de tenis 988', 'descripcion': 'Raqueta ligera para principiantes', 'cantidad': 20, 'precio': 200.39, 'categoria': 'Deportes'},
    {'nombre': 'Bicicleta 212', 'descripcion': 'Bicicleta de montaña con 18 velocidades', 'cantidad': 7, 'precio': 447.16, 'categoria': 'Deportes'},
    {'nombre': 'Guantes de boxeo 199', 'descripcion': 'Guantes acolchados para entrenamiento', 'cantidad': 13, 'precio': 358.49, 'categoria': 'Deportes'},
    {'nombre': 'Cuerda para saltar 635', 'descripcion': 'Cuerda ligera con mangos ergonómicos', 'cantidad': 22, 'precio': 482.51, 'categoria': 'Deportes'},
    {'nombre': 'Novela 222', 'descripcion': 'Novela de misterio de autor famoso', 'cantidad': 21, 'precio': 304.47, 'categoria': 'Libros'},
    {'nombre': 'Ciencia ficción 358', 'descripcion': 'Libro futurista con tecnología avanzada', 'cantidad': 35, 'precio': 10.54, 'categoria': 'Libros'},
    {'nombre': 'Poesía 839', 'descripcion': 'Colección de poemas clásicos', 'cantidad': 33, 'precio': 339.48, 'categoria': 'Libros'},
    {'nombre': 'Infantil 962', 'descripcion': 'Cuentos ilustrados para niños', 'cantidad': 25, 'precio': 427.81, 'categoria': 'Libros'},
    {'nombre': 'Cocina 571', 'descripcion': 'Recetas tradicionales del mundo', 'cantidad': 46, 'precio': 224.8, 'categoria': 'Libros'},
    {'nombre': 'Shampoo 969', 'descripcion': 'Shampoo para cabello seco', 'cantidad': 44, 'precio': 366.84, 'categoria': 'Belleza'},
    {'nombre': 'Crema facial 404', 'descripcion': 'Crema hidratante con vitamina E', 'cantidad': 18, 'precio': 357.3, 'categoria': 'Belleza'},
    {'nombre': 'Perfume 369', 'descripcion': 'Fragancia suave y duradera', 'cantidad': 38, 'precio': 445.28, 'categoria': 'Belleza'},
    {'nombre': 'Maquillaje 191', 'descripcion': 'Kit básico de maquillaje', 'cantidad': 31, 'precio': 61.75, 'categoria': 'Belleza'},
    {'nombre': 'Cepillo de pelo 502', 'descripcion': 'Cepillo con cerdas suaves', 'cantidad': 34, 'precio': 72.84, 'categoria': 'Belleza'},
    {'nombre': 'Sábanas 228', 'descripcion': 'Juego de sábanas de algodón', 'cantidad': 36, 'precio': 394.47, 'categoria': 'Hogar'},
    {'nombre': 'Cortina 659', 'descripcion': 'Cortina opaca de colores', 'cantidad': 13, 'precio': 103.83, 'categoria': 'Hogar'},
    {'nombre': 'Almohada 675', 'descripcion': 'Almohada ergonómica antialérgica', 'cantidad': 43, 'precio': 451.16, 'categoria': 'Hogar'},
    {'nombre': 'Taza 112', 'descripcion': 'Taza de cerámica decorativa', 'cantidad': 29, 'precio': 193.05, 'categoria': 'Hogar'},
    {'nombre': 'Mesa plegable 536', 'descripcion': 'Mesa compacta para espacios reducidos', 'cantidad': 45, 'precio': 270.44, 'categoria': 'Hogar'},
    {'nombre': 'Gorro 163', 'descripcion': 'Gorro de lana para invierno', 'cantidad': 24, 'precio': 162.66, 'categoria': 'Ropa'},
    {'nombre': 'Laptop 295', 'descripcion': 'Portátil ligera y potente para uso diario', 'cantidad': 3, 'precio': 160.16, 'categoria': 'Electrónica'},
    {'nombre': 'Laptop 621', 'descripcion': 'Portátil ligera y potente para uso diario', 'cantidad': 30, 'precio': 281.75, 'categoria': 'Electrónica'},
    {'nombre': 'Cepillo de pelo 851', 'descripcion': 'Cepillo con cerdas suaves', 'cantidad': 11, 'precio': 154.86, 'categoria': 'Belleza'},
    {'nombre': 'Bicicleta 598', 'descripcion': 'Bicicleta de montaña con 18 velocidades', 'cantidad': 29, 'precio': 132.48, 'categoria': 'Deportes'},
    {'nombre': 'Smartwatch 814', 'descripcion': 'Reloj inteligente con monitor de salud', 'cantidad': 33, 'precio': 238.01, 'categoria': 'Electrónica'},
    {'nombre': 'Infantil 841', 'descripcion': 'Cuentos ilustrados para niños', 'cantidad': 5, 'precio': 61.33, 'categoria': 'Libros'},
    {'nombre': 'Aceite 293', 'descripcion': 'Aceite vegetal de cocina', 'cantidad': 30, 'precio': 259.21, 'categoria': 'Alimentos'},
    {'nombre': 'Bicicleta 703', 'descripcion': 'Bicicleta de montaña con 18 velocidades', 'cantidad': 5, 'precio': 377.5, 'categoria': 'Deportes'},
    {'nombre': 'Zapatillas 538', 'descripcion': 'Zapatillas deportivas cómodas', 'cantidad': 20, 'precio': 245.52, 'categoria': 'Ropa'}
]